### ISSUE TITLE
[BUG] explicit box sizing css

### ISSUE THREAD

**Issue by arily** [umaxiaotian/Vue-PopupWindow#3]
## バグの説明
When used with tailwind CSS, border didn't take the width it should.

## 再現手順

- create Nuxt app
- install tailwind CSS Nuxt plugin

## 期待される動作
```css
.obaWindowStyle {
  box-sizing: content-box; /* was overwritten by tailwind default (also a lot of UI kit does this) */
}
```
## スクリーンショット
without explicit box sizing
![image](https://github.com/umaxiaotian/Vue-Window-Manager/assets/10007589/c53f8818-09d6-4054-8e79-c1b06c91b08f)
with explicit box sizing
![image](https://github.com/umaxiaotian/Vue-Window-Manager/assets/10007589/bb15e83a-f906-47ec-9f97-da1522cdf819)

## デスクトップ（以下の情報を入力してください）
 - OS：macOS
 - ブラウザ：Chrome
 - バージョン：119
